package io.github.toberocat.improvedFactions.core.gui.manager;

import io.github.toberocat.improvedFactions.core.player.CommandSender;
import io.github.toberocat.improvedFactions.core.player.ConsoleCommandSender;
import io.github.toberocat.improvedFactions.core.player.FactionPlayer;
import io.github.toberocat.improvedFactions.core.translator.Placeholder;
import io.github.toberocat.improvedFactions.core.utils.Logger;
import org.jetbrains.annotations.NotNull;

public interface BrowserGuiImplementation extends GuiImplementation {

    @Override
    default void openEditor(@NotNull CommandSender sender, @NotNull String guiId) {
        if (sender instanceof FactionPlayer<?> player)
            player.sendFancyMessage(translatable -> translatable
                            .getMessages()
                            .getMisc()
                            .get("gui-editor")
                            .get("send-browser-link"),
                    new Placeholder("link", generateLink(guiId))
            );
        else {
            Logger.api().logInfo("Copy & Paste the " +
                    "following link to edit your gui in the browser");
            Logger.api().logInfo(generateLink(guiId));
        }
    }

    private @NotNull String generateLink(@NotNull String guiId) {
        return "https://toberocat.github.io/ImprovedFactions_new/website/editor/editor.html?gui=eyJndWlUaXRsZVRyYW5zbGF0aW9uIjoibm9uZSIsInJvd3MiOjYsInN0YXRlcyI6WyJkZWZhdWx0U3RhdGUiXSwiaXRlbXMiOltbeyJkZWZhdWx0U3RhdGUiOnsiaWQiOiJhaXIiLCJ0cmFuc2xhdGlvbklkIjoibm9uZSJ9fSx7ImRlZmF1bHRTdGF0ZSI6eyJpZCI6ImFpciIsInRyYW5zbGF0aW9uSWQiOiJub25lIn19LHsiZGVmYXVsdFN0YXRlIjp7ImlkIjoiYWlyIiwidHJhbnNsYXRpb25JZCI6Im5vbmUifX0seyJkZWZhdWx0U3RhdGUiOnsiaWQiOiJhaXIiLCJ0cmFuc2xhdGlvbklkIjoibm9uZSJ9fSx7ImRlZmF1bHRTdGF0ZSI6eyJpZCI6ImFpciIsInRyYW5zbGF0aW9uSWQiOiJub25lIn19LHsiZGVmYXVsdFN0YXRlIjp7ImlkIjoiYWlyIiwidHJhbnNsYXRpb25JZCI6Im5vbmUifX0seyJkZWZhdWx0U3RhdGUiOnsiaWQiOiJhaXIiLCJ0cmFuc2xhdGlvbklkIjoibm9uZSJ9fSx7ImRlZmF1bHRTdGF0ZSI6eyJpZCI6ImFpciIsInRyYW5zbGF0aW9uSWQiOiJub25lIn19LHsiZGVmYXVsdFN0YXRlIjp7ImlkIjoiYWlyIiwidHJhbnNsYXRpb25JZCI6Im5vbmUifX1dLFt7ImRlZmF1bHRTdGF0ZSI6eyJpZCI6ImFpciIsInRyYW5zbGF0aW9uSWQiOiJub25lIn19LHsiZGVmYXVsdFN0YXRlIjp7ImlkIjoiYWlyIiwidHJhbnNsYXRpb25JZCI6Im5vbmUifX0seyJkZWZhdWx0U3RhdGUiOnsiaWQiOiJhaXIiLCJ0cmFuc2xhdGlvbklkIjoibm9uZSJ9fSx7ImRlZmF1bHRTdGF0ZSI6eyJpZCI6ImFpciIsInRyYW5zbGF0aW9uSWQiOiJub25lIn19LHsiZGVmYXVsdFN0YXRlIjp7ImlkIjoiYWlyIiwidHJhbnNsYXRpb25JZCI6Im5vbmUifX0seyJkZWZhdWx0U3RhdGUiOnsiaWQiOiJhaXIiLCJ0cmFuc2xhdGlvbklkIjoibm9uZSJ9fSx7ImRlZmF1bHRTdGF0ZSI6eyJpZCI6ImFpciIsInRyYW5zbGF0aW9uSWQiOiJub25lIn19LHsiZGVmYXVsdFN0YXRlIjp7ImlkIjoiYWlyIiwidHJhbnNsYXRpb25JZCI6Im5vbmUifX0seyJkZWZhdWx0U3RhdGUiOnsiaWQiOiJhaXIiLCJ0cmFuc2xhdGlvbklkIjoibm9uZSJ9fV0sW3siZGVmYXVsdFN0YXRlIjp7ImlkIjoiYWlyIiwidHJhbnNsYXRpb25JZCI6Im5vbmUifX0seyJkZWZhdWx0U3RhdGUiOnsiaWQiOiJhaXIiLCJ0cmFuc2xhdGlvbklkIjoibm9uZSJ9fSx7ImRlZmF1bHRTdGF0ZSI6eyJpZCI6ImFpciIsInRyYW5zbGF0aW9uSWQiOiJub25lIn19LHsiZGVmYXVsdFN0YXRlIjp7ImlkIjoiYWlyIiwidHJhbnNsYXRpb25JZCI6Im5vbmUifX0seyJkZWZhdWx0U3RhdGUiOnsiaWQiOiJhaXIiLCJ0cmFuc2xhdGlvbklkIjoibm9uZSJ9fSx7ImRlZmF1bHRTdGF0ZSI6eyJpZCI6ImFpciIsInRyYW5zbGF0aW9uSWQiOiJub25lIn19LHsiZGVmYXVsdFN0YXRlIjp7ImlkIjoiYWlyIiwidHJhbnNsYXRpb25JZCI6Im5vbmUifX0seyJkZWZhdWx0U3RhdGUiOnsiaWQiOiJhaXIiLCJ0cmFuc2xhdGlvbklkIjoibm9uZSJ9fSx7ImRlZmF1bHRTdGF0ZSI6eyJpZCI6ImFpciIsInRyYW5zbGF0aW9uSWQiOiJub25lIn19XSxbeyJkZWZhdWx0U3RhdGUiOnsiaWQiOiJhaXIiLCJ0cmFuc2xhdGlvbklkIjoibm9uZSJ9fSx7ImRlZmF1bHRTdGF0ZSI6eyJpZCI6ImFpciIsInRyYW5zbGF0aW9uSWQiOiJub25lIn19LHsiZGVmYXVsdFN0YXRlIjp7ImlkIjoiYWlyIiwidHJhbnNsYXRpb25JZCI6Im5vbmUifX0seyJkZWZhdWx0U3RhdGUiOnsiaWQiOiJhaXIiLCJ0cmFuc2xhdGlvbklkIjoibm9uZSJ9fSx7ImRlZmF1bHRTdGF0ZSI6eyJpZCI6ImFpciIsInRyYW5zbGF0aW9uSWQiOiJub25lIn19LHsiZGVmYXVsdFN0YXRlIjp7ImlkIjoiYWlyIiwidHJhbnNsYXRpb25JZCI6Im5vbmUifX0seyJkZWZhdWx0U3RhdGUiOnsiaWQiOiJhaXIiLCJ0cmFuc2xhdGlvbklkIjoibm9uZSJ9fSx7ImRlZmF1bHRTdGF0ZSI6eyJpZCI6ImFpciIsInRyYW5zbGF0aW9uSWQiOiJub25lIn19LHsiZGVmYXVsdFN0YXRlIjp7ImlkIjoiYWlyIiwidHJhbnNsYXRpb25JZCI6Im5vbmUifX1dLFt7ImRlZmF1bHRTdGF0ZSI6eyJpZCI6ImFpciIsInRyYW5zbGF0aW9uSWQiOiJub25lIn19LHsiZGVmYXVsdFN0YXRlIjp7ImlkIjoiYWlyIiwidHJhbnNsYXRpb25JZCI6Im5vbmUifX0seyJkZWZhdWx0U3RhdGUiOnsiaWQiOiJhaXIiLCJ0cmFuc2xhdGlvbklkIjoibm9uZSJ9fSx7ImRlZmF1bHRTdGF0ZSI6eyJpZCI6ImFpciIsInRyYW5zbGF0aW9uSWQiOiJub25lIn19LHsiZGVmYXVsdFN0YXRlIjp7ImlkIjoiYWlyIiwidHJhbnNsYXRpb25JZCI6Im5vbmUifX0seyJkZWZhdWx0U3RhdGUiOnsiaWQiOiJhaXIiLCJ0cmFuc2xhdGlvbklkIjoibm9uZSJ9fSx7ImRlZmF1bHRTdGF0ZSI6eyJpZCI6ImFpciIsInRyYW5zbGF0aW9uSWQiOiJub25lIn19LHsiZGVmYXVsdFN0YXRlIjp7ImlkIjoiYWlyIiwidHJhbnNsYXRpb25JZCI6Im5vbmUifX0seyJkZWZhdWx0U3RhdGUiOnsiaWQiOiJhaXIiLCJ0cmFuc2xhdGlvbklkIjoibm9uZSJ9fV0sW3siZGVmYXVsdFN0YXRlIjp7ImlkIjoiYWlyIiwidHJhbnNsYXRpb25JZCI6Im5vbmUifX0seyJkZWZhdWx0U3RhdGUiOnsiaWQiOiJhaXIiLCJ0cmFuc2xhdGlvbklkIjoibm9uZSJ9fSx7ImRlZmF1bHRTdGF0ZSI6eyJpZCI6ImFpciIsInRyYW5zbGF0aW9uSWQiOiJub25lIn19LHsiZGVmYXVsdFN0YXRlIjp7ImlkIjoiYWlyIiwidHJhbnNsYXRpb25JZCI6Im5vbmUifX0seyJkZWZhdWx0U3RhdGUiOnsiaWQiOiJhaXIiLCJ0cmFuc2xhdGlvbklkIjoibm9uZSJ9fSx7ImRlZmF1bHRTdGF0ZSI6eyJpZCI6ImFpciIsInRyYW5zbGF0aW9uSWQiOiJub25lIn19LHsiZGVmYXVsdFN0YXRlIjp7ImlkIjoiYWlyIiwidHJhbnNsYXRpb25JZCI6Im5vbmUifX0seyJkZWZhdWx0U3RhdGUiOnsiaWQiOiJhaXIiLCJ0cmFuc2xhdGlvbklkIjoibm9uZSJ9fSx7ImRlZmF1bHRTdGF0ZSI6eyJpZCI6ImFpciIsInRyYW5zbGF0aW9uSWQiOiJub25lIn19XV19";
    }
}
